In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('red_wine.csv')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
data.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [31]:
plt.hist(data.iloc[:,-1])

(array([ 10.,   0.,  53.,   0., 681.,   0., 638.,   0., 199.,  18.]),
 array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ]),
 <a list of 10 Patch objects>)

In [6]:
X = data.iloc[:,:-1]
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [7]:
y = data.iloc[:,-1]
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [9]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
892            10.1              0.45         0.23             1.9      0.082   
1017            8.0              0.18         0.37             0.9      0.049   
1319            9.1              0.76         0.68             1.7      0.414   
1053            8.3              0.33         0.42             2.3      0.070   
579            10.6              0.31         0.49             2.2      0.063   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
892                  10.0                  18.0  0.99774  3.22       0.65   
1017                 36.0                 109.0  0.99007  2.89       0.44   
1319                 18.0                  64.0  0.99652  2.90       1.33   
1053                  9.0                  20.0  0.99426  3.38       0.77   
579                  18.0                  40.0  0.99760  3.14       0.51   

      alcohol  
892       9.3  
1017     12.7  
1319      9.1  
1053     12.7  
579       9.8

In [10]:
X_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
694             9.0              0.47         0.31             2.7      0.084   
191             6.4              0.37         0.25             1.9      0.074   
967             8.5              0.66         0.20             2.1      0.097   
1399            7.2              0.67         0.00             2.2      0.068   
171             8.0              0.42         0.17             2.0      0.073   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
694                  24.0                 125.0  0.99840  3.31       0.61   
191                  21.0                  49.0  0.99740  3.57       0.62   
967                  23.0                 113.0  0.99733  3.13       0.48   
1399                 10.0                  24.0  0.99560  3.42       0.72   
171                   6.0                  18.0  0.99720  3.29       0.61   

      alcohol  
694       9.4  
191       9.8  
967       9.2  
1399     11.1  
171       9.2

In [11]:
print(X_train.shape,X_test.shape)
print(y_train.shape,y_test.shape)

(1279, 11) (320, 11)
(1279,) (320,)


In [12]:
from sklearn import linear_model

In [13]:
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
predictions = reg.predict(X_test)

In [15]:
predictions[0:5]

array([5.14097672, 5.46598921, 4.86255866, 5.80125463, 5.45020617])

In [16]:
reg.coef_

array([ 2.49905527e-02, -1.08359026e+00, -1.82563948e-01,  1.63312698e-02,
       -1.87422516e+00,  4.36133331e-03, -3.26457970e-03, -1.78811638e+01,
       -4.13653144e-01,  9.16334413e-01,  2.76197699e-01])

In [17]:
reg.intercept_

21.96520844944809